[tools]
asphalt = "jacktabscode/asphalt@0.8.1"
darklua = "seaofvoices/darklua@0.13.1"
lune = "lune-org/lune@0.8.8"
rojo = "rojo-rbx/rojo@7.4.4"
selene = "kampfkarren/selene@0.27.1"
# tarmac = "jeparlefrancais/tarmac@0.7.1"
